<script setup>
import { ref, defineEmits, computed } from 'vue';
import axios from 'axios';

const emit = defineEmits(['podcast-generated', 'document-processed']);

// --- Component State ---
const userThemes = ref('');
const generateAudio = ref(false);
const formStage = ref('initial');
const proposedThemes = ref([]);
const currentThreadId = ref(null);
const currentDocId = ref(null);
const isLoading = ref(false);
const apiError = ref(null);
const generationMode = ref('interactive');
const inputMode = ref('file');
const rawTextContent = ref('');
const autoGeneratedTopic = ref('');
const selectedPersona = ref('factual-finn');


// --- Document Processing Logic ---
const processDocument = async (docId, processingFunction) => {
    isLoading.value = true;
    apiError.value = null;
    autoGeneratedTopic.value = '';
    try {
        const response = await processingFunction();
        autoGeneratedTopic.value = response.data.topic_summary;
        currentDocId.value = docId;
        emit('document-processed', docId);
        apiError.value = null;
    } catch (error) {
        console.error("Error processing document:", error);
        apiError.value = error.response?.data?.detail || "Failed to process document.";
        currentDocId.value = null;
        autoGeneratedTopic.value = '';
        emit('document-processed', null);
    } finally {
        isLoading.value = false;
    }
};

const handleFileChange = async (event) => {
    const file = event.target.files[0];
    if (!file) return;
    const docId = `doc_${Date.now()}`;
    await processDocument(docId, () => {
        const formData = new FormData();
        formData.append('file', file);
        formData.append('doc_id', docId);
        return axios.post('http://127.0.0.1:8000/process_document_for_rag', formData);
    });
};

const handleTextSubmit = async () => {
    if (!rawTextContent.value.trim()) {
        apiError.value = "Please paste some text content before submitting.";
        return;
    }
    const docId = `doc_${Date.now()}`;
    await processDocument(docId, () => {
        const payload = {
            doc_id: docId,
            text_content: rawTextContent.value
        };
        return axios.post('http://127.0.0.1:8000/process_text_for_rag', payload);
    });
};

// --- Theme and Podcast Logic ---
const handleProposeThemes = async () => {
    if (!currentDocId.value) {
        apiError.value = "Please upload a file or submit text content first.";
        return;
    }
    apiError.value = null;
    isLoading.value = true;
    const themesArray = userThemes.value.split(',').map(theme => theme.trim()).filter(theme => theme.length > 0);
    const payload = {
        user_provided_themes: themesArray.length > 0 ? themesArray : null,
        doc_id: currentDocId.value,
    };
    try {
        const response = await axios.post('http://127.0.0.1:8000/propose_themes', payload);
        proposedThemes.value = response.data.themes;
        currentThreadId.value = response.data.thread_id;
        formStage.value = 'approval';
    } catch (error) {
        console.error("Error proposing themes:", error);
        apiError.value = error.response?.data?.detail || 'Failed to get themes.';
    } finally {
        isLoading.value = false;
    }
};

const handleInitiatePodcast = async () => {
    apiError.value = null;
    isLoading.value = true;
    const finalThemesArray = proposedThemes.value.join('\n').split('\n').filter(t => t.trim().length > 0);
    
    // UPDATED: Add the selected persona to the payload
    const payload = {
        final_themes: finalThemesArray,
        doc_id: currentDocId.value,
        generate_audio: generateAudio.value,
        generation_mode: generationMode.value,
        persona_name: selectedPersona.value // NEW
    };
    try {
        const response = await axios.post(`http://127.0.0.1:8000/initiate_podcast_flow/${currentThreadId.value}`, payload);
        emit('podcast-generated', {
            thread_id: currentThreadId.value,
            state: response.data
        });
    } catch (error) {
        console.error("Error initiating podcast:", error);
        apiError.value = error.response?.data?.detail || 'Failed to start podcast flow.';
    } finally {
        isLoading.value = false;
    }
};

const themesAsText = computed({
    get: () => proposedThemes.value.join('\n'),
    set: (value) => {
        proposedThemes.value = value.split('\n');
    }
});
</script>

<template>
    <div class="setup-form">
        <form @submit.prevent="handleProposeThemes" v-if="formStage === 'initial'">
            <h2>1. Provide Content</h2>
            <div class="input-mode-toggle">
                <button type="button" :class="{ active: inputMode === 'file' }" @click="inputMode = 'file'">Upload PDF</button>
                <button type="button" :class="{ active: inputMode === 'text' }" @click="inputMode = 'text'">Paste Text</button>
            </div>

            <div class="form-group" v-if="inputMode === 'file'">
                <label for="file-upload">Source Document (PDF):</label>
                <input type="file" id="file-upload" @change="handleFileChange" accept=".pdf" />
            </div>

            <div class="form-group" v-if="inputMode === 'text'">
                <label for="raw-text">Paste Your Article or Text:</label>
                <textarea id="raw-text" v-model="rawTextContent" rows="10" placeholder="Paste your content here..."></textarea>
                <button type="button" class="submit-text-btn" @click="handleTextSubmit" :disabled="isLoading">
                    {{ isLoading ? 'Processing...' : 'Submit Text' }}
                </button>
            </div>
            
            <div v-if="currentDocId" class="doc-success">✓ Content Processed Successfully!</div>
            <hr class="divider" />

            <h2>2. Setup Your Topic</h2>
            <div class="form-group" v-if="autoGeneratedTopic">
                <label>Generated Podcast Topic:</label>
                <p class="generated-topic">{{ autoGeneratedTopic }}</p>
            </div>
            <div class="form-group">
                <label for="user-themes">Optional: Provide Your Own Themes (comma-separated)</label>
                <input type="text" id="user-themes" v-model="userThemes" placeholder="e.g., history of the topic, future implications"/>
            </div>
            <button type="submit" :disabled="isLoading || !currentDocId">
                {{ isLoading ? 'Processing...' : 'Propose Guiding Themes' }}
            </button>
        </form>

        <form @submit.prevent="handleInitiatePodcast" v-if="formStage === 'approval'">
            <h2>3. Approve Guiding Themes</h2>
            <p>You can edit the AI-proposed themes below before starting the podcast.</p>
            <div class="form-group">
                <label for="final-themes">Guiding Themes (one per line):</label>
                <textarea id="final-themes" v-model="themesAsText" rows="6"></textarea>
            </div>

            <div class="form-group">
                <label for="persona-select">Choose Explainer Persona:</label>
                <select id="persona-select" v-model="selectedPersona" class="persona-select">
                    <option value="factual-finn">Factual Finn (Direct & Factual)</option>
                    <option value="example-eve">Example Eve (Example-Rich)</option>
                    <option value="analogy-alex">Analogy Alex (Analogies & Metaphors)</option>
                </select>
            </div>

            <div class="form-group">
                <label>Generation Mode:</label>
                <div class="radio-group">
                    <div class="radio-option">
                        <input type="radio" id="mode-interactive" value="interactive" v-model="generationMode">
                        <label for="mode-interactive">Interactive (Turn-by-Turn)</label>
                    </div>
                    <div class="radio-option">
                        <input type="radio" id="mode-bulk" value="bulk" v-model="generationMode">
                        <label for="mode-bulk">Bulk (Generate All at Once)</label>
                    </div>
                </div>
            </div>

            <div class="form-group-inline">
                <input type="checkbox" id="generate-audio" v-model="generateAudio" />
                <label for="generate-audio">Generate Audio for Each Turn?</label>
            </div>

            <button type="submit" :disabled="isLoading">
                {{ isLoading ? 'Starting...' : 'Confirm & Start Podcast' }}
            </button>
        </form>

        <div v-if="apiError" class="status-message error">
            Error: {{ apiError }}
        </div>
    </div>
</template>

<style scoped>
.persona-select {
    width: 100%;
    padding: 10px;
    border-radius: 4px;
    border: 1px solid #555;
    background-color: #3b3b3b;
    color: #f0f0f0;
    font-size: 1em;
    box-sizing: border-box;
}
.generated-topic {
    background-color: #3b3b3b;
    border: 1px solid #555;
    padding: 12px;
    border-radius: 4px;
    color: #f0f0f0;
    font-style: italic;
}
.setup-form {
    background-color: #2f2f2f;
    padding: 25px;
    border-radius: 8px;
    margin-bottom: 20px;
}
.form-group {
    margin-bottom: 20px;
    text-align: left;
}
.form-group-inline {
    margin-bottom: 20px;
    text-align: left;
    display: flex;
    align-items: center;
}
.form-group-inline input[type="checkbox"] {
    margin-right: 10px;
    width: auto;
}
label {
    display: block;
    margin-bottom: 8px;
    font-weight: bold;
    color: #ccc;
}
textarea, input[type="text"], input[type="file"] {
    width: 100%;
    padding: 10px;
    border-radius: 4px;
    border: 1px solid #555;
    background-color: #3b3b3b;
    color: #f0f0f0;
    font-size: 1em;
    box-sizing: border-box;
}
textarea {
    resize: vertical;
    font-family: inherit;
}
button {
    padding: 12px 25px;
    background-color: #007bff;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 1.1em;
    font-weight: bold;
    width: 100%;
}
button:hover:not(:disabled) {
    background-color: #0056b3;
}
button:disabled {
    background-color: #555;
    cursor: not-allowed;
}
.status-message {
    margin-top: 15px;
    padding: 10px;
    border-radius: 4px;
    text-align: center;
}
.error {
    background-color: #ffdddd;
    border: 1px solid #ff0000;
    color: #d8000c;
}
.doc-success {
    color: #28a745;
    font-weight: bold;
    margin-top: 8px;
    text-align: center;
}
h2 {
    border-bottom: 1px solid #444;
    padding-bottom: 10px;
    margin-bottom: 20px;
}
.divider {
    border: none;
    border-top: 1px solid #444;
    margin: 25px 0;
}
.radio-group {
    display: flex;
    gap: 20px;
    margin-top: 5px;
}
.radio-option {
    display: flex;
    align-items: center;
}
.radio-option input[type="radio"] {
    width: auto;
    margin-right: 8px;
}
.radio-option label {
    font-weight: normal;
    margin-bottom: 0;
}
.input-mode-toggle {
    display: flex;
    margin-bottom: 20px;
}
.input-mode-toggle button {
    flex: 1;
    padding: 10px;
    background-color: #444;
    border: 1px solid #555;
    color: #ccc;
    cursor: pointer;
    width: 50%;
}
.input-mode-toggle button:first-child {
    border-top-left-radius: 4px;
    border-bottom-left-radius: 4px;
}
.input-mode-toggle button:last-child {
    border-top-right-radius: 4px;
    border-bottom-right-radius: 4px;
}
.input-mode-toggle button.active {
    background-color: #007bff;
    color: white;
    border-color: #007bff;
}
.submit-text-btn {
    width: auto;
    margin-top: 10px;
    font-size: 0.9em;
    padding: 8px 15px;
}
</style>